name: ml-ci-cd-pipeline
on: [push]
jobs:
  train:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
        - uses: actions/checkout@v2
        - name: 'Train my model'
          env:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
          run: |
            pip install -r requirements.txt
            python src/pipes/trainer.py
            